apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  namespace: worker
  labels:
    app: worker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: munjo185/worker-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-url
        - name: QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: queue-secret
              key: queue-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
